name: AeroMaps
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  AeroMaps:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AeroMaps
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
    settings:
      INFOPLIST_FILE: AeroMaps/Info.plist
      INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Shows your location on the map"
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      DEVELOPMENT_ASSET_PATHS: '"AeroMaps/Preview Content"'
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      PRODUCT_BUNDLE_IDENTIFIER: com.example.AeroMaps
      PRODUCT_NAME: "$(TARGET_NAME)"
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: AeroMaps/Info.plist
      properties:
        CFBundleDisplayName: AeroMaps
        CFBundleIdentifier: com.example.AeroMaps
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
